In [ ]:
"""                           ASSIGNMENT 4      
Write a python program to create an array and perform addition of two matrices."""


In [4]:
## import numpy as np

def create_matrix(rows, cols, matrix_num):
    print(f"Enter the elements for Matrix {matrix_num} ({rows}x{cols}):")
    elements = []
    for i in range(rows):
        row = []
        for j in range(cols):
            val = float(input(f"Element [{i+1}][{j+1}]: "))
            row.append(val)
        elements.append(row)
    return np.array(elements)

def main():
    print("--- Matrix Addition Program ---")
    try:
        
        rows = int(input("Enter the number of rows: "))
        cols = int(input("Enter the number of columns: "))
        
        if rows <= 0 or cols <= 0:
            print("Matrix dimensions must be positive integers.")
            return

       
        matrix_A = create_matrix(rows, cols, 1)
        matrix_B = create_matrix(rows, cols, 2)
        
        result_matrix = matrix_A + matrix_B
        
        print("--- Matrix 1 ---")
        print(matrix_A)
        
        print("--- Matrix 2 ---")
        print(matrix_B)
        
        print("--- Resultant Matrix (Sum) ---")
        print(result_matrix)
        
    except ValueError:
        print("Invalid input! Please enter integers for dimensions and numbers for elements.")

main()

--- Matrix Addition Program ---


Enter the number of rows:  2
Enter the number of columns:  2


Enter the elements for Matrix 1 (2x2):


Element [1][1]:  1
Element [1][2]:  2
Element [2][1]:  3
Element [2][2]:  4


Enter the elements for Matrix 2 (2x2):


Element [1][1]:  4
Element [1][2]:  3
Element [2][1]:  2
Element [2][2]:  1


--- Matrix 1 ---
[[1. 2.]
 [3. 4.]]
--- Matrix 2 ---
[[4. 3.]
 [2. 1.]]
--- Resultant Matrix (Sum) ---
[[5. 5.]
 [5. 5.]]
